import random

from discord.ext import commands


class OneHeadMentalHealth(commands.Cog):

    quotes = [
        """“The advice I’d give to somebody that’s silently struggling is, you don’t have to live that way. You don’t have to struggle in silence. You can be un-silent. You can live well with a mental health condition, as long as you open up to somebody about it, because it’s really important you share your experience with people so that you can get the help that you need.” — Demi Lovato""",
        """“I found that with depression, one of the most important things you can realize is that you’re not alone. You’re not the first to go through it, you’re not gonna be the last to go through it,” — Dwayne “The Rock” Johnson""",
        """“I understand your pain. Trust me, I do. I’ve seen people go from the darkest moments in their lives to living a happy, fulfilling life. You can do it too. I believe in you. You are not a burden. You will NEVER BE a burden.” — Sophie Turner""",
        """“The experience I have had is that once you start talking about [experiencing a mental health struggle], you realize that actually you’re part of quite a big club.” — Prince Harry""",
        """“Anything that’s human is mentionable, and anything that is mentionable can be more manageable. When we can talk about our feelings, they become less overwhelming, less upsetting, and less scary.” — Fred Rogers""",
        """“There is hope, even when your brain tells you there isn’t.” ― John Green""",
        """“You look at me and cry; everything hurts. I hold you and whisper: but everything can heal.” ― Rupi Kaur""",
        """“The humanity we all share is more important than the mental illnesses we may not” ― Elyn R. Saks""",
        """“Life doesn’t make any sense without interdependence. We need each other, and the sooner we learn that, the better for us all.”  — Erik Erikson""",
        """“Mental health problems don’t define who you are. They are something you experience. You walk in the rain and you feel the rain, but, importantly, YOU ARE NOT THE RAIN.” — Matt Haig""",
        """“You are the one thing in this world, above all other things, that you must never give up on. When I was in middle school, I was struggling with severe anxiety and depression and the help and support I received from my family and a therapist saved my life. Asking for help is the first step. You are more precious to this world than you’ll ever know.” — Lili Rhinehart""",
        """“I would say what others have said: It gets better. One day, you’ll find your tribe. You just have to trust that people are out there waiting to love you and celebrate you for who you are. In the meantime, the reality is you might have to be your own tribe. You might have to be your own best friend. That’s not something they’re going to teach you in school. So start the work of loving yourself. — Wentworth Miller""",
        """“If you are broken, you do not have to stay broken.” — Selena Gomez""",
        """“My dark days made me stronger. Or maybe I already was strong, and they made me prove it.” — Emery Lord""",
        """“Sometimes the people around you won’t understand your journey. They don’t need to, it’s not for them.” — Joubert Botha""",
        """“You don’t have to be positive all the time. It’s perfectly okay to feel sad, angry, annoyed, frustrated, scared and anxious. Having feelings doesn’t make you a negative person. It makes you human.” — Lori Deschene""",
        """“This feeling will pass. The fear is real but the danger is not.” ― Cammie McGovern""",
        """“But no matter how much evil I see, I think it’s important for everyone to understand that there is much more light than darkness.” ― Robert Uttaro""",
        """“Tough times never last, but tough people do!” — Robert Schuller""",
        """“Many survivors insist they’re not courageous: ‘If I were courageous I would have stopped the abuse.’ ‘If I were courageous, I wouldn’t be scared’… Most of us have it mixed up. You don’t start with courage and then face fear. You become courageous because you face your fear.” ― Laura Davis""",
        """“I keep moving ahead, as always, knowing deep down inside that I am a good person and that I am worthy of a good life.” ― Jonathan Harnisch""",
        """“Happiness can be found even in the darkest of times, if one only remembers to turn on the light.” — Albus Dumbledore from Harry Potter and the Prisoner of Azkaban""",
        """“Be patient and tough; some day this pain will be useful to you.” — Ovid""",
        """“There is a crack in everything, that’s how the light gets in” ― Leonard Cohen""",
        """“Increasing the strength of our minds is the only way to reduce the difficulty of life.” ― Mokokoma Mokhonoana""",
        """“Not until we are lost do we begin to understand ourselves” ― Henry David Thoreau""",
        """“I am not afraid of storms for I am learning how to sail my ship.” — Amy March, from Little Women""",
        """“Sometimes you climb out of bed in the morning and you think, I’m not going to make it, but you laugh inside — remembering all the times you’ve felt that way.” — Charles Bukowski""",
        """“Promise me you’ll always remember — you’re braver than you believe, and stronger than you seem, and smarter than you think.” — Christopher Robin from Winnie the Pooh""",
        """“In the middle of winter I at last discovered that there was in me an invincible summer.”  — Albert Camus""",
        """“If you’re going through hell, keep going.” — Winston Churchill""",
        """“If you have been brutally broken but still have the courage to be gentle to other living beings, then you’re a badass with a heart of an angel.” — Keanu Reeves""",
        """“Part of my identity is saying no to things I don’t want to do… I check in with myself throughout the day and I say, ‘Do I really want to do this?’ and if the answer is no, then I don’t do it. And you shouldn’t either.” — Lady Gaga""",
        """“Mental health needs a great deal of attention. It’s the final taboo and it needs to be faced and dealt with.” — Adam Ant""",
        """“There isn’t anybody out there who doesn’t have a mental health issue, whether it’s depression, anxiety, or how to cope with relationships. Having OCD is not an embarrassment anymore – for me. Just know that there is help and your life could be better if you go out and seek the help.” — Howie Mandel""",
        """“Mental health is something that we all need to talk about, and we need to take the stigma away from it. So let’s raise the awareness. Let’s let everybody know it’s OK to have a mental illness and addiction problem.” — Demi Lovato""",
        """“Being vulnerable is actually a strength and not a weakness — that’s why more and more mental health is such an important thing to talk about. It’s the same as being physically sick. And when you keep all those things inside, when you bottle them up, it makes you ill.” — Cara Delevingne""",
        """“I say that publicly because I think it’s really important to take the stigma away from mental health… My brain and my heart are really important to me. I don’t know why I wouldn’t seek help to have those things be as healthy as my teeth. I go to the dentist. So why wouldn’t I go to a shrink?” — Kerry Washington""",
        """“What I love about therapy is that they’ll tell you what your blind spots are. Although that’s uncomfortable and painful, it gives you something to work with.” — Pink""",
        """“Anyone can be affected, despite their level of success or their place on the food chain. In fact, there is a good chance you know someone who is struggling with it since nearly 20% of American adults face some form of mental illness in their lifetime. So why aren’t we talking about it?” — Kristen Bell""",
        """“I was with someone recently who asked: ‘Well, don’t you think that if you do too much therapy it will take away your artistic process?’ And I told them: ‘The biggest lie that we’ve ever been sold is that we as artists have to stay in pain to create.'” — Katy Perry""",
        """“What mental health needs is more sunlight, more candor, and more unashamed conversation.” — Glenn Close""",
        """“Being able to be your true self is one of the strongest components of good mental health.” —  Dr. Lauren Fogel Mersy""",
        """“No amount of therapy can or self care can make up for scarcity of food & drink, time, or financial resources.” — Whitney Goodman, LMFT""",
        """“In any given moment, we have two options: to step forward into growth or to step back into safety.” — Abraham Maslow""",
        """“You don’t need to find a lesson in your trauma.” — Jordan Pickell, MCP RCC""",
        """“Just because no one else can heal or do your inner work for you doesn’t mean you can, should, or need to do it alone.” — Lisa Olivera""",
        """“Two things can be true. You can love your family and have deep wounds as a result of your family experiences.” — Nedra Glover Tawwab""",
        """“What if you moved through the world as if you were easy to be loved? Because I promise you, you are easy to love.” Sonalee Rashatwar, LCSW""",
        """“Take a deep breath to remember you are the child who lived through survival mode and the empowered adult who chose their healing.” — Dr. Nicole LePera""",
        """“‘Positive vibes only’ isn’t a thing. Humans have a wide range of emotions and that’s OK.” — Molly Bahr, LMHC""",
        """“No amount of support or generosity justifies someone treating you badly. This includes parents.” — Sarah Crosby""",
        """“I don’t regret opening up about what I went through [with depression], because, it sounds really cliché, but I have had women come up to me and say, ‘It meant so much to me.’ It means so much when you realize that someone was having a really hard time and feeling shame and was trying to hide this whole thing.” — Winona Ryder""",
        """“It’s my experience that people are a lot more sympathetic if they can see you hurting, and for the millionth time in my life I wish for measles or smallpox or some other easily understood disease just to make it easier on me and also on them.” ― Jennifer Niven""",
        """“Change what you can, manage what you can’t.” ― Raymond McCauley""",
        """“Because wherever I sat — on the deck of a ship or at a street café in Paris or Bangkok — I would be sitting under the same glass bell jar, stewing in my own sour air.” ― Sylvia Plath""",
        """“Mental health affects every aspect of your life. It’s not just this neat little issue you can put into a box.” — Shannon Purser""",
        """“Crazy isn’t being broken or swallowing a dark secret. It’s you or me amplified. If you ever told a lie and enjoyed it. If you ever wished you could be a child forever.” ― Susanna Kaysen""",
        """“The most beautiful people we have known are those who have known defeat, known suffering, known struggle, known loss, and have found their way out of the depths. These persons have an appreciation, a sensitivity, and an understanding of life that fills them with compassion, gentleness, and a deep loving concern. Beautiful people do not just happen.” — Elisabeth Kübler-Ross""",
        """“The acknowledgement of having suffered evil is the greatest step forward in mental health.” ― Stefan Molyneux""",
        """“I knew well enough that one could fracture one’s legs and arms and recover afterward, but I did not know that you could fracture the brain in your head and recover from that too.” ― Vincent van Gogh""",
        """“We are not our trauma. We are not our brain chemistry. That’s part of who we are, but we’re so much more than that.” ― Sam J. Miller""",
        """“If there is no struggle, there is no progress.” — Fredrick Douglass""",
        """“…we live in a world where if you break your arm, everyone runs over to sign your cast, but if you tell people you’re depressed, everyone runs the other way. That’s the stigma. We are so… accepting of any body part breaking down, other than our brains. And that’s ignorance. That’s pure ignorance. And that ignorance has created a world that doesn’t understand depression, that doesn’t understand mental health.” — Kevin Breel""",
        """“What people never understand is that depression isn’t about the outside; it’s about the inside.” ― Jasmine Warga""",
        """“The pain of severe depression is quite unimaginable to those who have not suffered it, and it kills in many instances because its anguish can no longer be borne. The prevention of many suicides will continue to be hindered until there is a general awareness of the nature of this pain.” ― William Styron""",
        """“So many people look at [my depression] as me being ungrateful, but that is not it — I can’t help it. There’s not much that I’m closed off about, and the universe gave me all that so I could help people feel like they don’t have to be something they’re not or feel like they have to fake happy. There’s nothing worse than being fake happy.” — Miley Cyrus""",
        """“There is so much pain in the world, and most of these people keep theirs secret, rolling through agonizing lives in invisible wheelchairs, dressed in invisible bodycasts.” ― Andrew Solomon""",
        """“Others imply that they know what it is like to be depressed because they have gone through a divorce, lost a job, or broken up with someone. But these experiences carry with them feelings. Depression, instead, is flat, hollow, and unendurable. It is also tiresome. People cannot abide being around you when you are depressed. They might think that they ought to, and they might even try, but you know and they know that you are tedious beyond belief: you are irritable and paranoid and humorless and lifeless and critical and demanding and no reassurance is ever enough. You’re frightened, and you’re frightening, and you’re ‘not at all like yourself but will be soon,’ but you know you won’t.” ― Kay Redfield Jamison""",
        """“When you come out of the grips of a depression there is an incredible relief, but not one you feel allowed to celebrate. Instead, the feeling of victory is replaced with anxiety that it will happen again, and with shame and vulnerability when you see how your illness affected your family, your work, everything left untouched while you struggled to survive. We come back to life thinner, paler, weaker … but as survivors. Survivors who don’t get pats on the back from coworkers who congratulate them on making it. Survivors who wake to more work than before because their friends and family are exhausted from helping them fight a battle they may not even understand. I hope to one day see a sea of people all wearing silver ribbons as a sign that they understand the secret battle, and as a celebration of the victories made each day as we individually pull ourselves up out of our foxholes to see our scars heal, and to remember what the sun looks like.” ― Jenny Lawson""",
        """“If you know someone who’s depressed please resolve to never ask them why. Depression isn’t a straightforward response to a bad situation; depression just is, like the weather. Try to understand the blackness, lethargy, hopelessness and loneliness they’re going through. Be there for them when they come through the other side. It’s hard to be a friend to someone who’s depressed, but it is one of the kindest, noblest and best things you will ever do.” — Stephen Fry""",
        """“Feeling your feelings will not lead to depression.” — Jordan Pickell, MCP RCC""",
        """“…if you rely solely on medication to manage depression or anxiety, for example, you have done nothing to train the mind, so that when you come off the medication, you are just as vulnerable to a relapse as though you had never taken the medication.” — Daniel Goleman""",
        """“Depression weighs you down like a rock in a river. You don’t stand a chance. You can fight and pray and hope you have the strength to swim, but sometimes, you have to let yourself sink. Because you’ll never know true happiness until someone or something pulls you back out of that river — and you’ll never believe it until you realize it was you, yourself who saved you.” ― Alysha Speer""",
        """“It’s possible to live well, feel well, and also find happiness with bipolar disorder or any other mental illness [you’re] struggling with.” — Demi Lovato""",
        """“One of the things that baffles me (and there are quite a few) is how there can be so much lingering stigma with regards to mental illness, specifically bipolar disorder. In my opinion, living with manic depression takes a tremendous amount of balls. Not unlike a tour of Afghanistan (though the bombs and bullets, in this case, come from the inside). At times, being bipolar can be an all-consuming challenge, requiring a lot of stamina and even more courage, so if you’re living with this illness and functioning at all, it’s something to be proud of, not ashamed of. They should issue medals along with the steady stream of medication.” — Carrie Fisher""",
        """“You are not your illness. You have an individual story to tell. You have a name, a history, a personality. Staying yourself is part of the battle.” — Julian Seifter""",
        """“I’m not the kind of person who likes to shout out my personal issues from the rooftops, but with my bipolar becoming public, I hope fellow sufferers will know it’s completely controllable. I hope I can help remove any stigma attached to it, and that those who don’t have it under control will seek help with all that is available to treat it.” — Catherine Zeta-Jones""",
        """“I am bipolar, and I am proud. And that is why I wanted to write a book. To shine a light on mental illness, to be vulnerable about the days I let it take control and paid dearly for it, and to tell anyone fighting a similar battle: You are not alone. You are not broken.” — AJ Lee""",
        """“My recovery from manic depression has been an evolution, not a sudden miracle.” — Patty Duke""",
        """“When under the strain of bipolar’s strongest symptoms, we certainly can make selfish decisions, but that doesn’t make us selfish people. In fact, because we have struggled and known such depths of darkness, our compassion runs deeper.” — Lyss Trayers""",
        """“I have to remind myself that not everyone else is to blame for how I feel. That my emotions do what they do and it’s not just because someone else made me feel that way. I try to stop where I am and look around myself before reacting.”  — Sarah Bleckman""",
        """“Life is like a piano; the white keys represent happiness and the black show sadness. But as you go through life’s journey, remember that the black keys also create music.” — Ehssan""",
        """“Though I am often in the depths of misery, there is still calmness, pure harmony and music inside me.” ― Vincent van Gogh""",
        """“I give them the suggestion Allow yourself morning. I tell them it means that today may have been a rolling ball of anxiety and trembling, a face wet and slick with tears, but if you can get to morning, if you can allow yourself a new day to encourage a change, then you can get through it. Allow yourself morning.” ― Bassey Ikpi""",
        """Learn more tips from therapists about how to manage anxiety.""",
        """“I now have no problem with anxiety, it was something I was dealing with in the band… People saw strength in that, and they didn’t seem to expect it from a guy, but they expect it from a female, which to me is crazy. We’re all human. People are often afraid to admit difficulties, but I don’t believe that there should be a struggle with anything that’s the truth.” — Zayn Malik""",
        """“Don’t let your mind bully your body into believing it must carry the burden of its worries.” — Astrid Alauda""",
        """“What does your anxiety do? It does not empty tomorrow of its sorrow, but it empties today of its strength. It does not make you escape the evil; it makes you unfit to cope with it if it comes.” ― Raymond L. Cramer""",
        """“If you want to conquer the anxiety of life, live in the moment, live in the breath.” — Amit Ray""",
        """“Good humor is a tonic for mind and body. It is the best antidote for anxiety and depression. It is a business asset. It attracts and keeps friends. It lightens human burdens. It is the direct route to serenity and contentment.” — Grenville Kleiser""",
        """“Nothing diminishes anxiety faster than action.” — Walter Anderson""",
        """“No amount of anxiety can change the future. No amount of regret can change the past.” — Karen Salmansohn""",
        """“Anxiety is a thin stream of fear trickling through the mind. If encouraged, it cuts a channel into which all other thoughts are drained.” — Arthur Somers Roche""",
        """“Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.” — Thich Nhat Hanh""",
        """“My anxiety doesn’t come from thinking about the future but from wanting to control it.” — Hugh Prather""",
        """“[Slow breathing] is like an anchor in the midst of an emotional storm: the anchor won’t make the storm goes away, but it will hold you steady until it passes. — Russ Harris""",
        """“Anxiety does not empty tomorrow of its sorrows, but only empties today of its strength.” — Charles Spurgeon""",
        """“Sometimes self care is exercise and eating right. Sometimes it’s spending time with loved ones or taking a nap. And sometimes it’s watching an entire season of TV in one weekend while you lounge around in your pajamas. Whatever soothes your soul.” — Nanea Hoffman """,
        """“The best thing you could do is master the chaos in you. You are not thrown into the fire, you are the fire.” — Mama Indigo""",
        """“Until you make the unconscious conscious, it will direct your life and you will call it fate.” — Carl Jung""",
        """“Start listening to the way you talk to yourself. These interactions will tell you how well you know yourself, how much you respect yourself, and what boundaries you are lacking.” — Sara Kuburic""",
        """“Pay careful attention to anything you try to hide.” — Gretchen Rubin""",
        """“As you reflect back on the previous weeks, months or year, look for moments you can celebrate too. There will be some, even if you have to look a little harder.” — Emily Coxhead""",
        """“When I don’t pay attention to my feelings, I tend to put up with situations and people longer than I should.” — Allyson Dinneen""",
        """“The gentlest reminder: You might not need to read another self-help book, attend another training, or bookmark another Instagram post as much as you need to listen to, trust, and practice what you already know. What if the answer you’re looking for is actually within you already?” — Lisa Olivera""",
        """“Deep breathing is our nervous system’s love language.” — Dr. Lauren Fogel Mersy""",
        """“Don’t believe everything you think.”  — Unknown""",
        """“You don’t have to control your thoughts. You just have to stop letting them control you.”  — Dan Millman""",
        """“That was the crux. You. Only you could work on you. Nobody could force you, and if you weren’t ready, then you weren’t ready, and no amount of open-armed encouragement was going to change that.” ― Norah Vincent""",

    ]

    @commands.has_role("IHL")
    @commands.command(aliases=['mh'])
    async def mental_health(self, ctx, name):
        """
        Provides mental health to the target player.
        """

        quote = random.choice(self.quotes)
        await ctx.send("**{}**\n {}".format(name, quote))
