[project]
name = "onehead"
version = "1.56.6-beta"
description = "A Dota 2 in-house league Discord bot."
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
keywords = ["dota", "discord", "inhouse"]

dependencies = [
    "aiohttp",
    "dacite",
    "discord.py>=2.1.0",
    "pynacl",
    "pytz",
    "structlog",
    "tabulate",
    "types-tabulate",
    "tinydb",
    "toml"
]

[project.optional-dependencies]
dev = [
    "black"
]
test = [
    "dpytest"
]

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["onehead"]
exclude = ["secrets"]

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = false